[build]
    publish = "build"
    command = "npm run build"

[[plugins]]
    package = "@netlify/plugin-nextjs"

[build.environment]
    NODE_VERSION = "20"

[context.production.environment]
    NODE_ENV = "production"