# Generated by Django 5.0.7 on 2024-07-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('client_name', models.CharField(max_length=60)),
                ('client_description', models.TextField(max_length=255)),
                ('project_goal', models.TextField(max_length=255)),
                ('experience', models.TextField(max_length=510)),
                ('outcome', models.TextField(max_length=255)),
                ('screenshot', models.ImageField(upload_to='')),
            ],
        ),
    ]
